import Head from 'next/head'
import Button from '@/components/button/Button'
import Categories from '@/components/categories/Categories'
import { TagsData } from '@/components/models/models'
import { DataTagQuetes } from '@/components/models/models'

export default function Home(data: DataTagQuetes) {

	const tagsData: TagsData = {
		tags: data.tags
	}

	return (	
  		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='w-full text-center h-screen'>
				<h1 className='pb-8'>Popular quotes</h1>
				<div className='mx-auto w-1/2  flex justify-evenly'>
					<div className='w-2/5 pr-3 pl-2'>
						{
							data.data.results.map((quote, i) => {
								return (
									<div key={quote._id} className=' mb-9'>
										<div className='flex gap-12 items-center'>
											<div className='flex gap-5 text-left'>
												<div className='w-96 text-lg'>“{quote.content}”<br/><span className='font-bold'>― {quote.author}</span></div>
											</div>
											<Button btnId={quote._id}/>	
										</div>
									</div>				 
								)
							})
						}
					</div>	
					<Categories tags={tagsData.tags}/>
				</div>
			</main>
  		</>
)
}


Home.getInitialProps = async () => {
	const responseTags = await fetch('https://api.quotable.io/tags')
	const jsonTags: DataTagQuetes[] = await responseTags.json()

	const response = await fetch(`https://api.quotable.io/quotes/?tags=famous-quotes`)
	const json: DataTagQuetes[] = await response.json()
	
	return {	
		data: json,
		tags: jsonTags
	}

}