import Head from 'next/head'
import Categories from '@/components/categories/Categories'
import { QuetesData } from '@/components/models/models'
import Buttons from '../button/Button'


export default function TagQuote(quetes: QuetesData) {

	const arrIdQuote: string[] = quetes.quetes.map(quote => {
		return quote._id
	})

	return (	
  		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='w-full text-center h-screen'>
				<h1 className='pb-8'>Popular quotes</h1>
				<div className='mx-auto w-1/2  flex justify-evenly'>
					<div className='w-2/5 pr-3 pl-2'>
						{
							quetes.quetes.map(quote => {
								return (
									<div key={quote._id} className=' mb-9'>
										<div className='flex gap-12 items-center'>
											<div className='flex gap-5 text-left'>
												<div className='w-96 text-lg'>“{quote.content}”<br/><span className='font-bold'>― {quote.author}</span></div>
											</div>
											<Buttons btnArrId={arrIdQuote} btnId={quote._id}/>	
										</div>
									</div>				 
								)
							})
						}
					</div>	
					<Categories tags={quetes.tags}/>
				</div>
			</main>
  		</>
	)	
}